# Generated by Django 3.2.7 on 2021-11-04 17:58

import contacts.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('email', models.EmailField(max_length=50, verbose_name='Пошта')),
                ('comment', models.TextField(blank=True, default='', max_length=150, verbose_name='Коментар')),
                ('is_sent', models.BooleanField(default=False, verbose_name='відгук відправлений')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='дата створення')),
                ('file', models.FileField(help_text='Завантажте pdf або doc документ', upload_to=contacts.models._upload_file_cv, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc'])], verbose_name='Файл')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='дата останнього збору')),
                ('record_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_user', to=settings.AUTH_USER_MODEL, verbose_name='користувач')),
            ],
        ),
    ]
