# Generated by Django 3.2.5 on 2021-09-14 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="напишіть ваше ім'я", max_length=50, verbose_name="ім'я")),
                ('email', models.EmailField(max_length=50)),
                ('comment', models.TextField(help_text='залиште коментар', max_length=150, verbose_name='коментар')),
                ('file', models.FileField(help_text='завантажте pdf або doc документ', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc'])], verbose_name='файл')),
            ],
        ),
    ]
