# Generated by Django 3.2.5 on 2021-09-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(help_text='вкажіть вашу пошту', max_length=50, verbose_name='пошта'),
        ),
    ]
