# Generated by Django 3.2.7 on 2021-09-30 10:00

import account.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_contact_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=150, verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Пошта'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='file',
            field=models.FileField(help_text='Завантажте pdf або doc документ', upload_to=account.models._upload_file_cv, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc'])], verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50, verbose_name="Ім'я"),
        ),
    ]
