# Generated by Django 3.2.7 on 2021-10-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210930_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
