# Generated by Django 3.2.7 on 2021-10-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_contact_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='new_contact',
            field=models.BooleanField(default=True),
        ),
    ]
