# Generated by Django 3.2.7 on 2021-10-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_record_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='дата створення'),
        ),
    ]
