# Generated by Django 3.2.7 on 2021-11-04 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_record_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
